eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 8081
conductor:
  grpc-server:
    enabled=false:
spring:
  cloud:
    config:
      uri: http://localhost:8888
      import: "optional:configserver:"
spring.config.import: "optional:configserver:"
